///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imageAppLogo = 'assets/image/app_logo.png';
  static const String imageBackground = 'assets/image/background.png';
  static const String imageDelivery = 'assets/image/delivery.png';
  static const String imageLunch = 'assets/image/lunch.png';
  static const String imageMarker = 'assets/image/marker.png';
  static const String imageMyLocation = 'assets/image/my_location.png';
  static const String imageNoOrders = 'assets/image/noOrders.png';
  static const String imageNoProduct = 'assets/image/noProduct.png';
  static const String imageQr = 'assets/image/qr.png';
  static const String imageSplash = 'assets/image/splash.png';
  static const String lottieClose = 'assets/lottie/close.json';
  static const String lottieEmptyBox = 'assets/lottie/empty-box.json';
  static const String lottieGirlEmpty = 'assets/lottie/girl_empty.json';
  static const String lottieNotFound = 'assets/lottie/not-found.json';
  static const String lottiePin = 'assets/lottie/pin.json';
  static const String lottieProcessing = 'assets/lottie/processing.json';
  static const String svgBalance = 'assets/svg/balance.svg';
  static const String svgMyLocation = 'assets/svg/my_location.svg';
}
